### ISSUE TITLE
Checksum Mismatch

### ISSUE THREAD

**Issue by ljsherlock** [valentinocossar/trellis-database-and-uploads-migration#5]
Really like the tool, but I'm stuck pushing to production.

TASK [Pull exported database from production to development (backup)] *************************************************************
System info:
  Ansible 2.3.1.0; Linux
  Trellis at "Option to install WP-CLI packages"
---------------------------------------------------
checksum mismatch
fatal: [production_host]: FAILED! => {"changed": false, "checksum": null, "dest": "/home/homesick/www/mysite.com/site/database_backup", "failed": true, "file": "/srv/www/mysite.com/current/mysite_com_production_2017_08_04_13_53_01.sql.gz", "md5sum": null, "remote_checksum": "15f981b00102f9be019082fb0e07168931f2ff95", "remote_md5sum": null}

**Comment by davidyv** [comment]
Hello,

I'm having exactly the same problem when pushing database to production:

```
...
TASK [Export production database before importing dump (backup)] ***************************************************************
changed: [production_host]

TASK [Pull exported database from production to development (backup)] **********************************************************
System info:
  Ansible 2.3.1.0; Darwin
  Trellis at "Option to install WP-CLI packages"
---------------------------------------------------
checksum mismatch
fatal: [production_host]: FAILED! => {"changed": false, "checksum": null, "dest": "/Users/MYNAME/projects/wordpress/sites/DOMAIN/SUBDOMAIN/database_backup", "failed": true, "file": "/srv/www/SUBDOMAIN/current/SUBDOMAIN_production_2017_08_09_10_21_39.sql.gz", "md5sum": null, "remote_checksum": "711dced49c84f1abbb30a22b56b627c63c28f45a", "remote_md5sum": null}
	to retry, use: --limit @/Users/MYNAME/projects/wordpress/sites/DOMAIN/trellis/database-push.retry

PLAY RECAP *********************************************************************************************************************
production_host            : ok=7    changed=4    unreachable=0    failed=1
```

**Comment by valentinocossar** [comment]
Hi, sorry for the delay, this is a known issue, I've provided a solution [here](https://github.com/valentinocossar/trellis-database-uploads-migration/issues/4). I'm quite sure that this issue is related to [this Ansible fix](https://github.com/ansible/ansible/issues/23900) and maybe setting `validate_checksum` to `false` fixes the problem. But I want to understand why checksum validation fails.

Thank you for your feedback! 👍

**Comment by seeReadCode** [comment]
Ok I think I found what's going on here: https://github.com/ansible/ansible/issues/27312

So if you add `/{{backup_file}}` to the destination path, this problem goes away.

**Comment by valentinocossar** [comment]
Seems that the problem was caused by a combination of this two issues: [ansible/ansible#23900](https://github.com/ansible/ansible/issues/23900) and [ansible/ansible#27312](https://github.com/ansible/ansible/issues/27312).

[This](https://github.com/valentinocossar/trellis-database-uploads-migration/commit/786b449fce0a8b762b61a5b5200ae18e1013f55e) new fix resolves the problem for me, tell me if there are other issues related to this thread or if this fix doesn't work for you. Thank you for the help.

**Comment by ljsherlock** [comment]
Thanks for fixing this. As someone new to Ansible, I was pulling my hair out trying to diagnose the problem.

I will try the fix later on.
